##注册中心的地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:1111/eureka/
##服务端口号
#server:
#  port: 9060
#
##提供者的服务名称--调用的时候根据改名称来调用对应服务的方法
#spring:
#  application:
#    name: service-a
